apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admin
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetty
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetty
  template:
    metadata:
      labels:
        app: kubetty
    spec:
      containers:
      - args:
        - -a
        - 0.0.0.0
        - -p
        - "8080"
        - -w
        - /bin/bash
        image: ghcr.io/avp-cloud/kubetty
        name: kubetty
      serviceAccountName: admin
---
apiVersion: v1
kind: Service
metadata:
  name: kubetty
  namespace: default
spec:
  ports:
  - name: tty
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubetty
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubetty
  namespace: default
spec:
  rules:
  - host:
    http:
      paths:
      - backend:
          service:
            name: kubetty
            port:
              number: 8080
        path: /
        pathType: Prefix
